begin;

set local search_path = public, extensions;

select plan(37);

select has_table('public', 'users', 'users table exists');
select has_table('public', 'farmer_leads', 'farmer leads table exists');
select has_table('public', 'dispatches', 'dispatches table exists');
select has_table('public', 'institutions', 'institutions table exists');
select has_table('public', 'pilots', 'pilots table exists');
select has_table('public', 'work_items', 'work items table exists');
select has_table('public', 'sales_payment_links', 'payment links table exists');

select ok(
  not exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relkind = 'r'
      and not c.relrowsecurity
  ),
  'every public application table has row-level security enabled'
);

select ok(
  not has_table_privilege('anon', 'public.sales_payment_links', 'select'),
  'anonymous users cannot read protected payment links'
);
select ok(
  has_table_privilege('authenticated', 'public.sales_payment_links', 'select'),
  'authenticated role has the table grant needed for policy checks'
);
select ok(
  exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'sales_payment_links'
      and policyname = 'sales_payment_links_sales_select'
      and roles = array['authenticated']::name[]
  ),
  'payment links keep their sales-only select policy'
);
select ok(
  to_regprocedure('public.is_salesperson()') is not null
    and to_regprocedure('public.is_rsm()') is not null
    and to_regprocedure('public.is_sales_head()') is not null,
  'sales role policy helpers exist'
);
select ok(
  not has_function_privilege('anon', 'public.is_admin()', 'execute'),
  'anonymous users cannot execute internal role helpers'
);
select ok(
  has_function_privilege('authenticated', 'public.is_admin()', 'execute'),
  'signed-in users retain role-helper access required by row-level security'
);
select ok(
  not has_function_privilege(
    'authenticated',
    'public.backfill_dispatch_work_items_batch(timestamptz,uuid,integer)',
    'execute'
  ),
  'signed-in users cannot invoke internal work-item backfills'
);
select ok(
  not has_function_privilege(
    'authenticated',
    'public.sync_dispatch_work_items()',
    'execute'
  ),
  'signed-in users cannot invoke internal trigger functions as RPCs'
);
select ok(
  (select 'search_path=pg_catalog' = any(coalesce(proconfig, '{}'::text[]))
   from pg_proc
   where oid = 'public.make_year_code(text,text)'::regprocedure),
  'year-code generation uses a fixed search path'
);
select ok(
  (select 'search_path=pg_catalog' = any(coalesce(proconfig, '{}'::text[]))
   from pg_proc
   where oid = 'public.set_updated_at()'::regprocedure),
  'updated-at trigger uses a fixed search path'
);
select ok(
  (
    select column_default like '%make_year_code%'
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'dispatches'
      and column_name = 'dispatch_code'
  ),
  'dispatch codes are generated by the database when omitted'
);

select ok(
  exists (
    select 1
    from storage.buckets
    where id = 'app-uploads'
      and public = false
  ),
  'application upload bucket exists and is private'
);
select is(
  (select file_size_limit from storage.buckets where id = 'app-uploads'),
  52428800::bigint,
  'application upload bucket has a 50 MB hard limit'
);
select is(
  (
    select count(*)::integer
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname in (
        'app_uploads_authenticated_read',
        'app_uploads_authenticated_insert',
        'app_uploads_owner_delete'
      )
  ),
  3,
  'application upload bucket has scoped read, insert, and cleanup policies'
);
select ok(
  (
    select 'image/heic' = any (allowed_mime_types)
    from storage.buckets
    where id = 'app-uploads'
  ),
  'application upload bucket accepts the HEIC type supported by the forms'
);
select ok(
  to_regprocedure('public.can_read_app_upload(text)') is not null
    and to_regprocedure('public.can_write_app_upload(text)') is not null,
  'application upload policy helpers exist'
);
select is(
  (
    select count(*)
    from public.get_sector_performance(null, null, null)
  ),
  3::bigint,
  'sector performance returns all three business sectors in one call'
);
select ok(
  exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'app_uploads_authenticated_read'
      and qual like '%can_read_app_upload%'
  )
    and exists (
      select 1
      from pg_policies
      where schemaname = 'storage'
        and tablename = 'objects'
        and policyname = 'app_uploads_authenticated_insert'
        and with_check like '%can_write_app_upload%'
    ),
  'application upload policies call the record and role scope helpers'
);
select is(
  (
    select count(*)::integer
    from pg_class index_relation
    join pg_index index_definition
      on index_definition.indexrelid = index_relation.oid
    join pg_namespace index_namespace
      on index_namespace.oid = index_relation.relnamespace
    where index_namespace.nspname = 'public'
      and index_relation.relname in (
        'uq_dispatches_active_device',
        'uq_dispatches_active_farmer_destination',
        'uq_dispatches_active_pilot_destination'
      )
      and index_definition.indisunique
      and index_definition.indpred is not null
  ),
  3,
  'active dispatch uniqueness is enforced for devices, farmer leads, and pilots'
);
select ok(
  exists (
    select 1
    from pg_class index_relation
    join pg_index index_definition
      on index_definition.indexrelid = index_relation.oid
    join pg_namespace index_namespace
      on index_namespace.oid = index_relation.relnamespace
    where index_namespace.nspname = 'public'
      and index_relation.relname = 'idx_visit_reports_submitter_date_active'
      and index_definition.indpred is not null
  ),
  'active visit reports have an owner-and-date index for role-scoped KPI counts'
);
select ok(
  not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname like 'app_uploads%'
      and 'anon' = any(roles)
  ),
  'application upload policies are not granted to anonymous users'
);
select ok(
  exists (
    select 1
    from pg_constraint
    where conrelid = 'public.dispatches'::regclass
      and conname = 'dispatch_payment_rule'
  ),
  'dispatch payment approval is enforced by a database constraint'
);

insert into public.users (id, full_name, email, role, must_change_password)
values
  (
    '10000000-0000-0000-0000-000000000001',
    'Payment Link Salesperson',
    'e2e-salesperson@jivawater.com',
    'Salesperson',
    false
  ),
  (
    '10000000-0000-0000-0000-000000000002',
    'Payment Link Viewer',
    'e2e-viewer@jivawater.com',
    'Viewer',
    false
  );

insert into public.sales_payment_links (
  product_name,
  offer_label,
  discount_percent,
  regular_price_inr,
  amount_inr,
  payment_url
)
values (
  'Test Product',
  'Regular price',
  0,
  100,
  100,
  'https://example.test/payment'
);

select set_config(
  'request.jwt.claims',
  '{"sub":"10000000-0000-0000-0000-000000000001","email":"e2e-salesperson@jivawater.com","role":"authenticated"}',
  true
);
set local role authenticated;
select is(
  (select count(*) from public.sales_payment_links),
  1::bigint,
  'a salesperson can read protected payment links through RLS'
);
select ok(
  public.can_write_app_upload(
    'farmer-leads/10000000-0000-4000-8000-000000000011/report/file.pdf'
  ),
  'a salesperson can upload to the Farmer Leads module'
);
select ok(
  not public.can_write_app_upload(
    'pilots/10000000-0000-4000-8000-000000000011/report/file.pdf'
  ),
  'a salesperson cannot upload directly to the Pilots module'
);
select ok(
  not public.can_write_app_upload('farmer-leads/not-a-uuid/report/file.pdf'),
  'upload writes reject malformed record paths'
);
reset role;

select set_config(
  'request.jwt.claims',
  '{"sub":"10000000-0000-0000-0000-000000000002","email":"e2e-viewer@jivawater.com","role":"authenticated"}',
  true
);
set local role authenticated;
select is(
  (select count(*) from public.sales_payment_links),
  0::bigint,
  'a viewer cannot read protected payment links through RLS'
);
select ok(
  not public.can_write_app_upload(
    'farmer-leads/10000000-0000-4000-8000-000000000012/report/file.pdf'
  ),
  'a viewer cannot upload application files'
);
reset role;

update public.users
set is_active = false
where id = '10000000-0000-0000-0000-000000000002';

set local role authenticated;
select ok(
  not public.can_write_app_upload(
    'farmer-leads/10000000-0000-4000-8000-000000000012/report/file.pdf'
  ),
  'a deactivated internal user cannot upload application files'
);
reset role;

select * from finish();
rollback;
