-- Expands crop_option for the classified crop library.
-- Safe to apply on production: no data is changed and existing crop values are preserved.

alter type public.crop_option add value if not exists 'Wheat';
alter type public.crop_option add value if not exists 'Maize';
alter type public.crop_option add value if not exists 'Sorghum (Jowar)';
alter type public.crop_option add value if not exists 'Pearl millet (Bajra)';
alter type public.crop_option add value if not exists 'Finger millet (Ragi)';
alter type public.crop_option add value if not exists 'Barley';
alter type public.crop_option add value if not exists 'Small millets (Foxtail, Little, Kodo, Barnyard, Proso)';
alter type public.crop_option add value if not exists 'Chickpea (Gram)';
alter type public.crop_option add value if not exists 'Pigeon pea (Red gram/Tur)';
alter type public.crop_option add value if not exists 'Green gram (Moong)';
alter type public.crop_option add value if not exists 'Black gram (Urad)';
alter type public.crop_option add value if not exists 'Field pea';
alter type public.crop_option add value if not exists 'Cowpea';
alter type public.crop_option add value if not exists 'Horse gram';
alter type public.crop_option add value if not exists 'Lablab bean';
alter type public.crop_option add value if not exists 'Groundnut';
alter type public.crop_option add value if not exists 'Soybean';
alter type public.crop_option add value if not exists 'Mustard';
alter type public.crop_option add value if not exists 'Sesame';
alter type public.crop_option add value if not exists 'Sunflower';
alter type public.crop_option add value if not exists 'Castor';
alter type public.crop_option add value if not exists 'Oil palm';
alter type public.crop_option add value if not exists 'Cotton';
alter type public.crop_option add value if not exists 'Tobacco';
alter type public.crop_option add value if not exists 'Jute';
alter type public.crop_option add value if not exists 'Mesta';
alter type public.crop_option add value if not exists 'Sunn hemp';
alter type public.crop_option add value if not exists 'Cashew';
alter type public.crop_option add value if not exists 'Rubber';
alter type public.crop_option add value if not exists 'Cocoa';
alter type public.crop_option add value if not exists 'Silver oak';
alter type public.crop_option add value if not exists 'Napier grass';
alter type public.crop_option add value if not exists 'Sorghum (fodder)';
alter type public.crop_option add value if not exists 'Maize (fodder)';
alter type public.crop_option add value if not exists 'Cowpea (fodder)';
alter type public.crop_option add value if not exists 'Coriander';
alter type public.crop_option add value if not exists 'Cumin';
alter type public.crop_option add value if not exists 'Fenugreek';
alter type public.crop_option add value if not exists 'Mango';
alter type public.crop_option add value if not exists 'Citrus';
alter type public.crop_option add value if not exists 'Guava';
alter type public.crop_option add value if not exists 'Pomegranate';
alter type public.crop_option add value if not exists 'Papaya';
alter type public.crop_option add value if not exists 'Pineapple';
alter type public.crop_option add value if not exists 'Sapota';
alter type public.crop_option add value if not exists 'Aonla';
alter type public.crop_option add value if not exists 'Watermelon';
alter type public.crop_option add value if not exists 'Muskmelon';
alter type public.crop_option add value if not exists 'Avocado';
alter type public.crop_option add value if not exists 'Strawberry';
alter type public.crop_option add value if not exists 'Tomato';
alter type public.crop_option add value if not exists 'Brinjal (Eggplant)';
alter type public.crop_option add value if not exists 'Okra';
alter type public.crop_option add value if not exists 'Chilli';
alter type public.crop_option add value if not exists 'Capsicum';
alter type public.crop_option add value if not exists 'Cucumber';
alter type public.crop_option add value if not exists 'Bitter gourd';
alter type public.crop_option add value if not exists 'Bottle gourd';
alter type public.crop_option add value if not exists 'Ridge gourd';
alter type public.crop_option add value if not exists 'Sponge gourd';
alter type public.crop_option add value if not exists 'Snake gourd';
alter type public.crop_option add value if not exists 'Pumpkin';
alter type public.crop_option add value if not exists 'Ash gourd';
alter type public.crop_option add value if not exists 'Cabbage';
alter type public.crop_option add value if not exists 'Cauliflower';
alter type public.crop_option add value if not exists 'Broccoli';
alter type public.crop_option add value if not exists 'Knol-khol';
alter type public.crop_option add value if not exists 'Potato';
alter type public.crop_option add value if not exists 'Onion';
alter type public.crop_option add value if not exists 'Garlic';
alter type public.crop_option add value if not exists 'Carrot';
alter type public.crop_option add value if not exists 'Beetroot';
alter type public.crop_option add value if not exists 'Radish';
alter type public.crop_option add value if not exists 'Turnip';
alter type public.crop_option add value if not exists 'Sweet potato';
alter type public.crop_option add value if not exists 'Tapioca (Cassava)';
alter type public.crop_option add value if not exists 'Elephant foot yam';
alter type public.crop_option add value if not exists 'Hyacinth bean';
alter type public.crop_option add value if not exists 'French bean';
alter type public.crop_option add value if not exists 'Cluster bean';
alter type public.crop_option add value if not exists 'Dolichos bean';
alter type public.crop_option add value if not exists 'Garden pea';
alter type public.crop_option add value if not exists 'Broad bean';
alter type public.crop_option add value if not exists 'Spinach';
alter type public.crop_option add value if not exists 'Amaranthus';
alter type public.crop_option add value if not exists 'Lettuce';
alter type public.crop_option add value if not exists 'Celery';
alter type public.crop_option add value if not exists 'Marigold';
alter type public.crop_option add value if not exists 'Rose';
alter type public.crop_option add value if not exists 'Jasmine';
alter type public.crop_option add value if not exists 'Chrysanthemum';
alter type public.crop_option add value if not exists 'Tuberose';
alter type public.crop_option add value if not exists 'Gerbera';
alter type public.crop_option add value if not exists 'Carnation';
alter type public.crop_option add value if not exists 'Orchid';
alter type public.crop_option add value if not exists 'Gladiolus';
alter type public.crop_option add value if not exists 'Lilium';
alter type public.crop_option add value if not exists 'Ginger';
